"""Initial database schema with 5 tables

Revision ID: 74f3b4e63934
Revises: 
Create Date: 2026-01-17 05:27:16.848689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f3b4e63934'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('subscription_ends_at', sa.DateTime(), nullable=True),
    sa.Column('monthly_generation_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_generations_used', sa.Integer(), nullable=False),
    sa.Column('monthly_cost_limit_usd', sa.Float(), nullable=False),
    sa.Column('monthly_cost_used_usd', sa.Float(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('world_id', sa.String(), nullable=True),
    sa.Column('default_genre', sa.String(length=50), nullable=True),
    sa.Column('default_production_type', sa.String(length=50), nullable=True),
    sa.Column('narrative_count', sa.Integer(), nullable=False),
    sa.Column('total_word_count', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_projects_world_id'), 'projects', ['world_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('production_brief', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('completed_stages', sa.JSON(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('actual_cost_usd', sa.Float(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('can_resume', sa.Boolean(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_celery_task_id'), 'generation_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_project_id'), 'generation_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_status'), 'generation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_generation_jobs_user_id'), 'generation_jobs', ['user_id'], unique=False)
    op.create_table('narratives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('production_type', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('quality_metrics', sa.JSON(), nullable=True),
    sa.Column('overall_quality_score', sa.Float(), nullable=True),
    sa.Column('generation_cost_usd', sa.Float(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_narrative_id', sa.String(), nullable=True),
    sa.Column('exported_formats', sa.JSON(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_narrative_id'], ['narratives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narratives_genre'), 'narratives', ['genre'], unique=False)
    op.create_index(op.f('ix_narratives_job_id'), 'narratives', ['job_id'], unique=False)
    op.create_index(op.f('ix_narratives_production_type'), 'narratives', ['production_type'], unique=False)
    op.create_index(op.f('ix_narratives_project_id'), 'narratives', ['project_id'], unique=False)
    op.create_index(op.f('ix_narratives_user_id'), 'narratives', ['user_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('production_type', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('mini_tokens', sa.Integer(), nullable=False),
    sa.Column('gpt4_tokens', sa.Integer(), nullable=False),
    sa.Column('mini_cost_usd', sa.Float(), nullable=False),
    sa.Column('gpt4_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_job_id'), 'usage_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_project_id'), 'usage_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_project_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_job_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_narratives_user_id'), table_name='narratives')
    op.drop_index(op.f('ix_narratives_project_id'), table_name='narratives')
    op.drop_index(op.f('ix_narratives_production_type'), table_name='narratives')
    op.drop_index(op.f('ix_narratives_job_id'), table_name='narratives')
    op.drop_index(op.f('ix_narratives_genre'), table_name='narratives')
    op.drop_table('narratives')
    op.drop_index(op.f('ix_generation_jobs_user_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_status'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_project_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_celery_task_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_projects_world_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
